name: pr
on: [ pull_request ]
jobs:
  check-race:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          # https://www.npmjs.com/package/semver#caret-ranges-123-025-004
          go-version: '^1.17'
      - run: go version
      - run: sudo apt-get install redis-server
      - run: make deps
      - run: make check-race
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          # https://www.npmjs.com/package/semver#caret-ranges-123-025-004
          go-version: '^1.17'
      - run: go version
      - run: sudo apt-get install redis-server
      - run: make deps
      - run: make check-fmt
      - run: make vet
      - run: make staticcheck
      - run: make cicheck
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.14'
      - run: cd packaging
      - run: export LATEST_VERSION=$(git describe --tags --always | awk -F \- '{print $1}')
      - run: export CUR_PART=$(echo $LATEST_VERSION | awk -F . '{print $1"."$2}')
      - run: export VERSION_PART=$(cat VERSION)
      - run: export OLD_PATCH=$(echo $LATEST_VERSION | awk -F . '{print $3}')
      - run: export NEW_PATCH=$((OLD_PATCH + 1))
      - run: export if [ "$CUR_PART" != "$VERSION_PART" ]; then NEW_PATCH=0; fi
      - run: export RELEASE_VERSION=${VERSION_PART}.${NEW_PATCH}
      - run: export VERSION="${RELEASE_VERSION}"
      - run: IMAGE=registry-write.opensource.zalan.do/pathfinder/skipper:${RELEASE_VERSION}
      - run: make docker.build.arm64
      - run: make docker.build.armv7
      - run: make docker.build.amd64
